base_url = "https://til.hanlho.com"
title = "Hanlho. Today I Learned"
description = "A collection of concise write-ups on small things I learn day to day."
author = "Hans L'Hoest"
compile_sass = false
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
author_name = "Hans L'Hoest"
github_repo = "https://github.com/lhohan/til"

[[taxonomies]]
name = "topics"
feed = true
paginate_by = 20
